const NYT_SEARCH_RESULT_RETRIEVED = "NEWS/NYT_SEARCH_RESULT_RETRIEVED";
const SHOW_MODAL_BOX = "NEWS/SHOW_MODAL_BOX";
const HIDE_MODAL_BOX = "NEWS/HIDE_MODAL_BOX";

export default {
    NYT_SEARCH_RESULT_RETRIEVED,
    SHOW_MODAL_BOX,
    HIDE_MODAL_BOX
}